### ISSUE TITLE
Error while executing lintPhp

### ISSUE THREAD

**Issue by sfroemkenjw** [astehlik/typo3-extension-buildtools#1]
Hello,

I get following error while executing lintPhp:

`Can't find a suitable configuration file in this directory or any parent. Are you in the right directory?`

I found this line which contains a `typo3/` folder:

https://github.com/astehlik/typo3-extension-buildtools/blob/main/testing-docker/docker-compose.yml#L718

Nice greetings

Stefan

**Comment by sfroemkenjw** [comment]
I have updated that part to:

```
    command: >
      /bin/sh -c "
        if [ ${SCRIPT_VERBOSE} -eq 1 ]; then
          set -x
        fi
        php -v | grep '^PHP'
        find *.php Classes Configuration Tests -name '*.php' -print0 | xargs -0 -n1 -P4 php -dxdebug.mode=off -l >/dev/null
      "
```

**Comment by astehlik** [comment]
Thank you, @sfroemkenjw 

This should now be fixed in all branches.
