### ISSUE TITLE
Error while executing cgl check

### ISSUE THREAD

**Issue by sfroemkenjw** [astehlik/typo3-extension-buildtools#2]
Hello,

I get following error while executing `cgl`:

`Can't find a suitable configuration file in this directory or any parent. Are you in the right directory?`

I found this line which contains a typo3/ folder:

https://github.com/astehlik/typo3-extension-buildtools/blob/main/testing-docker/docker-compose.yml#L412-L413

Nice greetings

Stefan

**Comment by sfroemkenjw** [comment]
I have updated that part to:

```
    command: >
      /bin/sh -c "
        if [ ${SCRIPT_VERBOSE} -eq 1 ]; then
          set -x
        fi
        php -dxdebug.mode=off ${CORE_ROOT}/.Build/bin/php-cs-fixer fix -v ${CGLCHECK_DRY_RUN} --path-mode intersection \
          --config=Build/php-cs-fixer/config.php Classes/ Tests/
      "
```

Works now.

Stefan

**Comment by sfroemkenjw** [comment]
I prefer using the same path as TYPO3 have:

https://github.com/TYPO3/typo3/tree/main/Build/php-cs-fixer

I have updated my answer above

**Comment by astehlik** [comment]
Hi @sfroemkenjw.

In the TYPO3_11 and TYPO3_12 branches the path is now completly removed, which gives you the greatest flexibility. You can configure the path in the config file.

You can find a working Example [here](https://github.com/astehlik/typo3-extension-tinyurls/blob/develop/Build/php-cs-fixer/config.php).

Please let me know if this is a viable solution for you.

**Comment by sfroemkenjw** [comment]
Hello @astehlik 

I had a talk to Stefan Bürk and migrated our new extensions completely to TYPO3 Testing Framework. So, I can't tell you anymore, if that will work.

Nice greetings 

Stefan
